import type { Message, Room } from './types.js';
/** Persisted membership deliberately has no online flag. */
export type StoredMember = { roomId: string; userId: string; displayName: string };
export type SaveMessageInput = {
  roomId: string; senderId: string; senderName: string; clientMessageId: string; text: string;
};
/** IDs/timestamps generated by the database owner. Methods reject on storage failure.
 * saveMessage atomically enforces (roomId, senderId, clientMessageId) uniqueness
 * and returns the original Message on retry. listMessages orders by createdAt, then id.
 */
export interface RoomDatabase {
  createRoom(input: { name: string }): Promise<Room>;
  getRoom(roomId: string): Promise<Room | null>;
  upsertMember(input: StoredMember): Promise<StoredMember>;
  listMembers(roomId: string): Promise<StoredMember[]>;
  listMessages(roomId: string): Promise<Message[]>;
  saveMessage(input: SaveMessageInput): Promise<Message>;
}
/** Persist sessions across restarts; send only userId in HTTP JSON.
 * The random sessionId is the HttpOnly cookie credential, separate from userId.
 * Both HTTP and Socket.IO must verify it with getSession before trusting userId.
 */
export type AnonymousSession = { sessionId: string; userId: string };
export interface SessionStore {
  createSession(): Promise<AnonymousSession>;
  getSession(sessionId: string): Promise<AnonymousSession | null>;
}
export type Database = RoomDatabase & SessionStore & { close(): void };
export type ServerDependencies = { database: RoomDatabase; sessions: SessionStore };
